name: SSH Execution Test
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  workflow_dispatch:
  #  push:
  #    branches:
  #      - "main"
jobs:
  Test-SSH-Actions:
    runs-on: macos-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
#      - name: Check out repository code
#        uses: actions/checkout@v3
#      - name: List files in the repository
#        run: |
#          ls ${{ github.workspace }}
      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.PODSPEC_SSH_KEY }}